---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mytomee
  labels:
    app: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      name: mytomee
      labels:
        app: appserver
    spec:
      containers:
        - name: mytomee
          image: tomee
          ports:
            - containerPort: 8080
              hostPort: 9090
...
