---
apiVersion: v1
kind: Pod
metadata:
  name: multi
spec:
  containers:
    - name: mydb
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 3030
    - name: webserver
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 3000
...
