---
apiVersion: v1
kind: Pod
metadata:
  name: tomee-pod
  labels:
    web: appswerver
    author: sun
spec:
  containers: 
    - name: webserver
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 9090
...

