---
apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    author: sun
    type: mydb
spec:
  containers:
    - name: mypostgres
      image: postgres
      env:
        - name: POSTGRES_PASSWORD
          value: sunny
        - name: POSTGRES_USER
          value: sunny
...  










