---
apiVersion: v1
kind: Pod
metadata:
  name: myjenkins
  labels:
    author: sun
    type: webserver
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins
      ports:
        - containerPort: 8080
          hostPort: 9999
...
