---
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    type: appserver
    author: tomcat
spec:
  containers:
    - name: mytomcat
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 7070
...

