---
apiVersion: v1
kind: Pod
metadata:
  name: mytomee
  namespace: test-ns
  labels: 
    type: webserver
    authour: sun
spec:
  containers:
    - name: mytomee
      image: tomee
      ports:
        - containerPort: 8080
          hostPort: 9090
...
