---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mypod
  labels:
    type: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      type: webserver
  template:
    metadata:
        name: mypod
        labels:
          type: webserver
    spec:
        containers:
          - name: mypod
            image: jenkins/jenkins
            ports:
              - containerPort: 8080
                hostPort: 9090
...                  

