apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcat-pod
  labels:
    app: appserver
spec:
  replicas: 2
  selector:
    matchLabels:
      app: appserver
  template:
    metadata:
      name: tomcat-pod
      labels:
        app: appserver
    spec:
      containers:
        - name: tomcat-pod
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 9090
...                
