---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins
  labels:
    type: webserver
    author: sunn
spec:
  replicas: 2
  template:
    metadata:
      name: myjenkins
      labels:
        app: webserver
    spec:
      containers:
        - name: myjenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
              hostPort: 9090
...
