---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    author: sun
    type: weserver
spec:
  type: NodePort
  ports:
    - targetPort: 8080
      port: 8080
      nodePort: 30009
  selector:
    author: sun
    type: weserver 
...
